apiVersion: apps/v1
kind: Deployment

metadata:
  name: commerce-deployment
  namespace: commerce

spec:
  replicas: 2

  selector:
    matchLabels:
      app: commerce

  template:
    metadata:
      labels:
        app: commerce

    spec:
      containers:
      - name: commerce-container
        image: nginx:latest

        ports:
        - containerPort: 80
